### ISSUE TITLE
CPCv2 augmentations

### ISSUE THREAD

**Issue by annione** [rschwarz15/ContrastivePredictiveCoding#5]
Hello,
great work! I'm currently trying to re-create the CPC v2 augmentations for a Tensorflow project and found your implementation very helpful regarding the AutoAugment transformations.
Are you planning on implementing the remaining CPC v2 augmentations as well? I'm currently stuck trying to figure out what the authors could have meant with the "color-histogram automentations by de Fauw et al.".

Kind regards

**Comment by rschwarz15** [comment]
Hi Annione,

Great to hear that this project has been helpful to you.

I recall trying to find those augmentations in the De Fauw et al. paper, but I believe they do not mention it. They do say: "Additionally, although we are unable to make all the Google proprietary components available, we are in the process of making the augmentation operations for TensorFlow available in the official TensorFlow code". So, I suspect it was never described in the paper but was accessed internally. It's possible they have now added this to TF.

Hopefully that helps. 

Regards,
Ronen

**Comment by annione** [comment]
Thank you for the reply!  I contacted the author of the paper in the  
meantime and he replied pretty much immediately! If you're interested,  
the elastic deformation and color augmentation has been implemented  
here:
https://github.com/deepmind/multidim-image-augmentation
The documentation section is quite good I think, however, the most  
important parts are implemented in C and have to be built with Bazel.  
Furthermore, the implementation relies on Tensorflow 1.  It pretty  
much took me a whole week to get it to work for Tensorflow 2.3, so I  
don't know how difficult it would be to transfer the approach to  
PyTorch (or if you're even interested in transferring it, for that  
manner :) )
